import { createContext, createElement, useContext } from "react";

export const LanguageContext = createContext("en");
const HI = {
"Home":"होम", "Find Standard":"मानक खोजें", "Upload Tender":"निविदा अपलोड करें", "How It Works":"यह कैसे काम करता है", "History":"इतिहास", "Login":"लॉगिन",
"Construction":"निर्माण", "Electrical":"विद्युत", "Plumbing":"प्लंबिंग", "Category":"श्रेणी", "Main navigation":"मुख्य नेविगेशन", "Skip to content":"मुख्य सामग्री पर जाएँ",
"INDIAN STANDARDS, MADE CLEAR":"भारतीय मानक, अब समझना आसान", "Find the right":"सही भारतीय", "Indian Standard.":"मानक खोजें।", "Before you procure.":"खरीद से पहले।",
"Describe what you’re buying or bring your tender.":"उत्पाद का विवरण दें या अपनी निविदा अपलोड करें।", "Find relevant IS codes. Understand why they matter.":"संबंधित IS कोड खोजें और उनकी उपयोगिता समझें।",
"Find a standard":"मानक खोजें", "Start with a product description.":"उत्पाद के विवरण से शुरुआत करें।", "Describe your requirement":"अपनी आवश्यकता बताएँ", "Review a tender":"निविदा की समीक्षा करें", "Let your procurement PDF do the talking.":"अपनी निविदा PDF से संबंधित मानक खोजें।", "Upload your PDF":"अपनी PDF अपलोड करें",
"Search through":"खोजें", "7261 Records":"7261 रिकॉर्ड में", "EXAMPLE PREVIEW":"उदाहरण", "YOUR REQUIREMENT":"आपकी आवश्यकता", "RECOMMENDED STANDARD":"अनुशंसित मानक", "Why this standard?":"यह मानक क्यों?", "CONNECTING THE DETAILS":"विवरण का मिलान", "Know what":"जानें क्या", "applies.":"लागू है।", "The code. The scope. The reason.":"कोड। दायरा। कारण।", "FROM YOUR REQUIREMENT TO A RELEVANT IS CODE":"आपकी आवश्यकता से संबंधित IS कोड तक",
"FIND STANDARD":"मानक खोजें", "Your requirement.":"आपकी आवश्यकता।", "The right starting point.":"सही शुरुआत।", "Tell us what you need, and explore the standards that may apply.":"अपनी आवश्यकता बताएँ और संबंधित मानक देखें।", "Product description":"उत्पाद का विवरण", "Describe the product, material and intended use…":"उत्पाद, सामग्री और उपयोग का विवरण लिखें…", "Clear":"साफ करें", "Include material, voltage or intended use. Enter to search · Shift+Enter for a new line.":"सामग्री, वोल्टेज या उपयोग बताएँ। खोजने के लिए Enter · नई पंक्ति के लिए Shift+Enter।", "Finding standards":"मानक खोजे जा रहे हैं", "Try a search":"उदाहरण से खोजें",
"Fly ash cement":"फ्लाई ऐश सीमेंट", "White cement":"सफेद सीमेंट", "Cement testing":"सीमेंट परीक्षण", "Building cables":"भवन की वायरिंग केबल", "Circuit breakers":"सर्किट ब्रेकर", "Electrical switches":"विद्युत स्विच", "Drinking water pipes":"पेयजल पाइप", "Hot water pipes":"गर्म पानी के पाइप", "Water storage tanks":"जल भंडारण टैंक",
"Your recommendations will appear here.":"अनुशंसित मानक यहाँ दिखाई देंगे।", "Your recommendations will appear here":"अनुशंसित मानक यहाँ दिखाई देंगे", "Select a code to view its scope and details.":"दायरा और विवरण देखने के लिए कोड चुनें।", "Recommended standards":"अनुशंसित मानक", "Select a code to explore its details.":"विवरण देखने के लिए कोड चुनें।", "A little more detail will help.":"कृपया थोड़ा और विवरण दें।", "Searching for:":"इसके लिए खोज:", "No suitable standard found":"उपयुक्त मानक नहीं मिला", "Try adding the material and intended use, or explore the BIS catalogue.":"सामग्री और उपयोग का विवरण जोड़ें या BIS सूची देखें।", "Explore BIS catalogue ↗":"BIS सूची देखें ↗",
"STANDARD OVERVIEW":"मानक का विवरण", "Scope":"दायरा", "Why recommended":"अनुशंसा का कारण", "Amendments":"संशोधन", "Amendment":"संशोधन", "Reaffirmed":"पुनर्पुष्टि", "Standard type":"मानक का प्रकार", "Status shown":"दर्शाई गई स्थिति", "Certification":"प्रमाणन", "Replacement":"प्रतिस्थापन", "Source checked on":"स्रोत जाँच की तारीख", "Catalogue retrieved":"सूची प्राप्त करने की तारीख", "Not recorded":"दर्ज नहीं है", "Copy IS code":"IS कोड कॉपी करें", "View BIS source":"BIS स्रोत देखें", "Code copied":"कोड कॉपी किया गया", "Select the code above to copy it.":"कॉपी करने के लिए ऊपर का कोड चुनें।", "Close dialog":"विवरण बंद करें",
"Open the BIS source to review the scope for this standard.":"इस मानक का दायरा देखने के लिए BIS स्रोत खोलें।", "The standard title is related to your description. Review its scope for the intended use.":"मानक का शीर्षक आपके विवरण से संबंधित है। उपयोग के अनुसार उसका दायरा जाँचें।", "Applicability depends on the product and relevant order.":"लागू होने की स्थिति उत्पाद और संबंधित आदेश पर निर्भर करती है।", "Confirm technical applicability and the current edition before citing a standard in a tender.":"निविदा में मानक का उल्लेख करने से पहले उसकी तकनीकी उपयुक्तता और वर्तमान संस्करण की पुष्टि करें।",
"Related standards and references":"संबंधित मानक और संदर्भ", "References":"संदर्भ", "Referenced by":"इनमें संदर्भित", "Show fewer":"कम दिखाएँ",
"Finding relevant standards":"संबंधित मानक खोजे जा रहे हैं", "Reviewing your description":"आपके विवरण की समीक्षा", "Checking spelling and common aliases":"वर्तनी और प्रचलित नामों की जाँच", "Comparing semantic similarity":"अर्थ की समानता का मिलान", "Matching keywords and IS codes":"मुख्य शब्दों और IS कोड का मिलान", "Applying category rules and ranking":"श्रेणी के नियम और क्रम लागू करना",
"Reviewing your tender":"निविदा की समीक्षा जारी है", "Finding the relevant Indian Standards":"संबंधित भारतीय मानक खोजना", "Reading the tender PDF":"निविदा PDF पढ़ना", "Identifying the product and grade":"उत्पाद और ग्रेड की पहचान", "Matching cited Indian Standards":"उल्लिखित भारतीय मानकों का मिलान", "Loading BIS record and related test methods":"BIS रिकॉर्ड और संबंधित परीक्षण विधियाँ लोड करना",
"UPLOAD TENDER":"निविदा अपलोड करें", "One tender.":"एक निविदा।", "A clearer set of standards.":"मानकों की स्पष्ट सूची।", "Upload a searchable tender PDF to identify its product requirements and relevant Indian Standards.":"उत्पाद की आवश्यकताएँ और संबंधित भारतीय मानक खोजने के लिए टेक्स्ट वाली निविदा PDF अपलोड करें।", "Upload tender PDF":"निविदा PDF अपलोड करें", "PDF accepted":"PDF स्वीकार की गई", "Remove selected PDF":"चुनी गई PDF हटाएँ", "Checking the document and finding relevant standards…":"दस्तावेज़ की जाँच और संबंधित मानकों की खोज जारी है…", "PDF ready. Click Find Standard to begin the review.":"PDF तैयार है। समीक्षा शुरू करने के लिए मानक खोजें पर क्लिक करें।", "Drop your PDF here":"अपनी PDF यहाँ छोड़ें", "Drag & drop your tender PDF":"निविदा PDF खींचकर यहाँ छोड़ें", "Or choose a file from your device":"या अपने डिवाइस से फ़ाइल चुनें", "Accepting PDF…":"PDF स्वीकार की जा रही है…", "Reviewing tender…":"निविदा की समीक्षा जारी है…", "Choose another PDF":"दूसरी PDF चुनें", "Choose PDF":"PDF चुनें", "Choose tender PDF":"निविदा PDF चुनें", "Searchable PDF · Up to 10 MB · Scanned PDFs and images are not supported":"टेक्स्ट वाली PDF · अधिकतम 10 MB · स्कैन PDF और चित्र समर्थित नहीं हैं",
"DOCUMENT WORKSPACE":"दस्तावेज़ कार्यक्षेत्र", "Read and review":"पढ़ें और समीक्षा करें", "Document view":"दस्तावेज़ दृश्य", "Full view":"पूरा दृश्य", "Split view":"विभाजित दृश्य", "Results only":"केवल परिणाम", "Tender PDF preview":"निविदा PDF का पूर्वावलोकन", "Open in new tab":"नए टैब में खोलें", "Uploaded tender PDF":"अपलोड की गई निविदा PDF", "Preview not displaying? Use Open in new tab to view or download your PDF.":"पूर्वावलोकन नहीं दिख रहा? PDF देखने या डाउनलोड करने के लिए नए टैब में खोलें।", "Click Find Standard above to review this tender across all three categories.":"तीनों श्रेणियों में समीक्षा के लिए ऊपर मानक खोजें पर क्लिक करें।", "TENDER REVIEW":"निविदा समीक्षा", "Preparing PDF…":"PDF तैयार की जा रही है…", "Export report":"रिपोर्ट डाउनलोड करें", "RECOMMENDATION":"अनुशंसा", "Category to confirm":"श्रेणी की पुष्टि आवश्यक", "No supported standard match found":"समर्थित मानक नहीं मिला", "Try a clearer searchable PDF or enter the product description in Find Standard.":"स्पष्ट टेक्स्ट वाली PDF दें या मानक खोजें में उत्पाद का विवरण लिखें।", "Review notes":"समीक्षा टिप्पणियाँ",
"A CLEARER WAY TO SEARCH":"खोजने का आसान तरीका", "From specification":"उत्पाद विवरण से", "to":"तक", "standard.":"मानक।", "Four steps to a better-informed procurement decision.":"बेहतर जानकारी के साथ खरीद के निर्णय के लिए चार चरण।", "Start with what you need":"अपनी आवश्यकता से शुरू करें", "Describe your product and choose a category, or upload a searchable tender PDF. Include the material and intended use.":"उत्पाद का विवरण और श्रेणी चुनें या टेक्स्ट वाली निविदा PDF अपलोड करें। सामग्री और उपयोग बताएँ।", "Find relevant candidates":"संबंधित मानक खोजें", "Keyword and semantic search compare your requirement with the collected standards catalogue.":"मुख्य शब्द और अर्थ आधारित खोज आपकी आवश्यकता का मानकों की सूची से मिलान करती है।", "Bring the best matches forward":"सबसे उपयुक्त परिणाम पहले", "Category filtering and ranking put the most relevant candidates first. More specific requirements help narrow the results.":"श्रेणी और क्रम के आधार पर संबंधित मानक पहले दिखते हैं। स्पष्ट विवरण खोज को बेहतर बनाता है।", "Understand before you procure":"खरीद से पहले समझें", "Open an IS code to review its scope, the reason for the match, and available amendment and reaffirmation details.":"IS कोड खोलकर दायरा, अनुशंसा का कारण, संशोधन और पुनर्पुष्टि के उपलब्ध विवरण देखें।", "Have a requirement in mind?":"क्या आपकी कोई आवश्यकता है?", "Find your standard":"अपना मानक खोजें",
"YOUR WORKSPACE":"आपका कार्यक्षेत्र", "Good work deserves":"आपकी पिछली खोजें", "a place to come back to.":"एक ही जगह।", "Recent searches and tender reviews from this browser tab. Up to 12 entries.":"इस ब्राउज़र टैब की हाल की खोजें और निविदा समीक्षाएँ। अधिकतम 12 प्रविष्टियाँ।", "Session history":"सत्र का इतिहास", "Clear history":"इतिहास मिटाएँ", "Standards search":"मानकों की खोज", "Tender review":"निविदा समीक्षा", "A fresh start":"नई शुरुआत", "Your searches and tender reviews will appear here.":"आपकी खोजें और निविदा समीक्षाएँ यहाँ दिखाई देंगी।", "Clarity before you procure.":"खरीद से पहले स्पष्टता।", "Explore BIS":"BIS देखें",
"ACCOUNT ACCESS":"खाते तक पहुँच", "Your workspace, without a login.":"बिना लॉगिन आपका कार्यक्षेत्र।", "Standards search and tender review are available now. Account sign-in and cross-device history are not connected in this version.":"मानक खोज और निविदा समीक्षा उपलब्ध हैं। इस संस्करण में खाता लॉगिन और अन्य डिवाइस पर इतिहास की सुविधा जुड़ी नहीं है।", "Continue to Find Standard":"मानक खोजें पर जाएँ",
"Cannot reach the backend. Check that it is running on port 8000.":"बैकएंड से संपर्क नहीं हो पा रहा। जाँचें कि वह पोर्ट 8000 पर चल रहा है।", "This request took too long. Please try again with a shorter requirement or PDF.":"अनुरोध में अधिक समय लगा। छोटे विवरण या PDF के साथ फिर प्रयास करें।"
};
export function translate(text, language) {
  if (language !== "hi" || typeof text !== "string") return text;
  const key = text.trim();
  const translated = HI[key];
  if (translated) return text.replace(key, translated);
  if (/^Show \d+ more$/.test(key)) return key.replace(/^Show (\d+) more$/, "$1 और दिखाएँ");
  if (/^\d+ listed$/.test(key)) return key.replace(/ listed$/, " दर्ज");
  if (/^Rank \d+$/.test(key)) return key.replace(/^Rank /, "क्रम ");
  if (/^\d+(\.\d+)? MB · PDF selected$/.test(key)) return key.replace("PDF selected", "PDF चुनी गई");
  return text;
}
function LocalizedNode({ tag, nodeProps, children }) {
  const language = useContext(LanguageContext);
  const props = { ...nodeProps };
  for (const name of ["placeholder", "title", "aria-label", "alt"]) {
    if (props[name]) props[name] = translate(props[name], language);
  }
  // Only display text is translated. Values, handlers, query payloads and identifiers are unchanged.
  const convert = value => Array.isArray(value) ? value.map(convert) : translate(value, language);
  return createElement(tag, props, convert(children));
}
export function localizedElement(tag, props, ...children) {
  if (typeof tag !== "string" || ["svg","path","circle","rect","line","polyline","polygon"].includes(tag)) return createElement(tag, props, ...children);
  return createElement(LocalizedNode, { key: props?.key, tag, nodeProps: props }, ...children);
}
